replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "bwoogmy/kbot"
  tag: "v1.1.1-be2a2a6"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
service:
  port: 80
  type: ClusterIP
autoscaling:
  enabled: false
serviceAccount:
  create: true
ingress:
  enabled: false
  # hosts: []
