name: KBOT-CICD

on: 
    push:
      branches: 
        - develop


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run test
        run: make test

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: make image

      - name: Push Docker image
        run: make push

      - name: Show image name
        run: |
          echo "IMAGE: ghcr.io/bwoogmy/kbot:$(make --quiet print-version)"

